#!/bin/sh

cmd_resolve() {
	snippet="$(printf "%s" "$1" | tr -d ' ')"
	case "$snippet" in
	*"@"*)
		head="$(printf "%s" "$snippet" | cut -d@ -f2)"
		snippet="$(printf "%s" "$snippet" | cut -d@ -f1)"
		;;
	*)
		head="main"
		;;
	esac
	commit="$(get_current_commit_sha "$head")"
	name="$(basename "$snippet")"
	echo "# POSIX-shell-include: $snippet@$commit"
	curl --silent "https://raw.githubusercontent.com/caioariede/POSIX-shell-include/$commit/$snippet/$name.sh"
}

cmd_rewrite() {
	AWK_SCRIPT="$(
		cat <<EOF
tolower(\$0) ~ /# posix-shell-include: (.+)/ {
    line=tolower(\$0)
    if (gsub("# posix-shell-include: ", "$opt_executable -r ", line) > 0) {
        while ( ( line | getline result ) > 0 ) {
            print result
        }
        close(cmd)
        next
    }
}
{ print }
EOF
	)"

	awk "$AWK_SCRIPT"
}

get_current_commit_sha() {
	curl --silent "https://api.github.com/repos/caioariede/POSIX-shell-include/commits/$1" | while read -r line; do
		case "$line" in
		*'"sha":'*)
			printf "%s" "$line" | cut -d\" -f4
			exit 0
			;;
		esac
	done
}

opt_executable="$0"
opt_cmd="cmd_rewrite"
opt_arg1=""

argc="$#"
argi=0
while [ $argi -lt $argc ]; do
	arg="$1"
	argi=$((argi + 1))
	shift
	case "$arg" in
	-i)
		opt_cmd="cmd_rewrite_inplace"
		;;
	-r)
		opt_cmd="cmd_resolve"
		;;
	*)
		opt_arg1="$arg"
		;;
	esac
done

case "$opt_cmd" in
cmd_resolve)
	cmd_resolve "$opt_arg1"
	;;
cmd_rewrite)
	cmd_rewrite <"$opt_arg1"
	;;
cmd_rewrite_inplace)
	tmpfile="$(mktemp)"
	cmd_rewrite <"$opt_arg1" >"$tmpfile"
	cat "$tmpfile" >"$opt_arg1"
	;;
esac
